name: CI

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.gitignore'

jobs:
  build:
    uses: Platform-System/Platform.CI-CD/.github/workflows/build-dotnet.yml@main
    secrets: inherit
    with:
      project_path: 'Platform.StoreImageUpload.Function.csproj'
      test_path: 'Platform.StoreImageUpload.Function.Tests/Platform.StoreImageUpload.Function.Tests.csproj'
      dependencies: 'Platform-System/Platform.Contracts'
